name: Resync fork
on:
  push:
    branches:
    - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git remote add upstream https://github.com/projectdiscovery/nuclei.git
          
          git checkout -b resync_fork origin/main
          git fetch upstream
          git pull --rebase -X theirs
          git status
          